### ISSUE TITLE
Disable .jpg or .png / original image extension generation when webp is enabled

### ISSUE THREAD

**Issue by naufalfarras** [TristanMouchet/laravel-mix-simple-image-processing#2]
Hi thank you for creating this plugin, but it is possible to add new feature to disable original extension when `webp` option is set to `true`?

**Comment by ojvribeiro** [comment]
This would be nice to have.

**Comment by TristanMouchet** [comment]
Hi, thank you for your interest in this plugin!

Sorry for the late reply, I have been quite busy lately! I made some changes that will allow you to generate WebP images without files with the original extensions (in version `1.0.8`).

Please review the new parameters and examples in the README here: https://github.com/TristanMouchet/laravel-mix-simple-image-processing

You will basically have to set `processOriginalImage` to `false` for default images when `webp` is `true` (or `thumbnailsWebpOnly` to `true` for thumbnails when `thumbnailsSizes` is set and `thumbnailsWebp` is `true`).

Note: Changes are retro-compatible so they will not break any existing setup.

**Comment by naufalfarras** [comment]
awesome! thankss Tristan!
