### ISSUE TITLE
Create destination folder if it doesn't exist

### ISSUE THREAD

**Issue by ojvribeiro** [TristanMouchet/laravel-mix-simple-image-processing#7]
When we try to use a non existing folder as the destination, we get an error like this:

![image](https://user-images.githubusercontent.com/8026741/192078563-2bef11c6-e423-41df-8907-24869abf2926.png)

It would be nice if a folder were created automatically if it doesn't exist.

**Comment by TristanMouchet** [comment]
Hi! This should now be the case in the new version (from version `1.0.8`). 👍

**Comment by ojvribeiro** [comment]
Nice! Thank you for this plugin. ❤️

**Comment by ojvribeiro** [comment]
~~Does the 1.0.8 have a release date?~~

**Comment by ojvribeiro** [comment]
Oh, I see there's a [`1.0.8` already on NPM](https://www.npmjs.com/package/laravel-mix-simple-image-processing/v/1.0.8).
