### ISSUE TITLE
Bigger images generated even with `smallerThumbnailsOnly`

### ISSUE THREAD

**Issue by ojvribeiro** [TristanMouchet/laravel-mix-simple-image-processing#8]
With this options:

```js
mix.imgs({
    source: 'assets/img',
    destination: '_dist/assets/img',
    thumbnailsSizes: [1920, 1200, 900, 600, 300, 50],
    processOriginalImage: true,
    smallerThumbnailsOnly: true,
})
```

I'm getting the following:

![image](https://user-images.githubusercontent.com/8026741/201820248-2b5a198e-dc0c-4d65-8c21-29da8a1941c0.png)

Shouldn't I get only a 50px image for the 140px wide image?

**Comment by TristanMouchet** [comment]
Thanks for noticing, sorry some changes were somehow removed from the last updates, I've pushed them back.

It should be working again if you `npm update` or update to the version `1.0.9` of the package. 👍

**Comment by ojvribeiro** [comment]
Oh, thanks a lot for that ❤️

**Comment by ojvribeiro** [comment]
Oh, something wrong happened here after I updated to `1.0.9`. It is trying to unlink a `300px` that does not exist and this error occurs:

![image](https://user-images.githubusercontent.com/8026741/202015595-b3ba9548-5542-4e47-bd60-21104a47514f.png)

Also, I got the right images for some and not for others:
![image](https://user-images.githubusercontent.com/8026741/202016481-dc634ad7-0927-4c73-9ad5-368a1e98b20a.png)
![image](https://user-images.githubusercontent.com/8026741/202016776-e65dfef0-1c35-426f-a3c1-da48144a9009.png)
![image](https://user-images.githubusercontent.com/8026741/202016743-ef74dd10-5859-4c50-9aeb-25e6bd84179d.png)

**Comment by ojvribeiro** [comment]
# Update

I got it to work with this config:

```js
mix.imgs({
  source: 'demo/assets/img',
  destination: 'demo/_dist/assets/img',
  thumbnailsSizes: [1920, 1200, 900, 600, 300, 50],
  thumbnailsWebpOnly: true,
  imageminWebpOptions: {
    quality: 90,
  },
})
```

BUT...

![image](https://user-images.githubusercontent.com/8026741/202022916-bc89c4ce-290d-4617-b18d-ecfa462dd487.png)

**Comment by TristanMouchet** [comment]
I just fixed the issue with thumbnails not being deleted properly when `smallerThumbnailsOnly` is set to `true`.

Note that `thumbnailsWebp` must be set to `true` if you want to set `thumbnailsWebpOnly` to `true`.

Also note that the package is not deleting the existing files when it is running, so you might want to clean the destination folder manually before running it (if you generated files with a wrong config before).

Last version of the package is now `1.0.10` 🙂

**Comment by ojvribeiro** [comment]
Great! It seems to be working great now. Thank you again for the support, Tristan!
